### ISSUE TITLE
Epic Part 2: Fix Errors Frontend Issue for DriverAvailability  

### ISSUE THREAD

**Issue by diyaparm** [ucsb-cs156-s24/proj-gauchoride-s24-5pm-6#31]
_### As a...

driver

### I can...

Undestand what each of the form fields mean

### So that...

i can submit a correct availability without running into issues

### Discussion

Frontend issue 1:
![image](https://github.com/ucsb-cs156/proj-gauchoride/assets/56096744/6a0b28e6-8e93-4763-a44f-59ce76db184e)
There is no 'bad-input' error messages. We should have error messages on bad input for `Day`, `Start Time`, `End Time`. For day it would be ideal to convert this field to a dropdown, similar to the one on the `RideRequestForm`.

Frontend issue 2:
Like the `RideRequestForm` we want to have example messages on each of the form fields to help making it easier for the driver to know how to fill it out
Example:
![image](https://github.com/ucsb-cs156/proj-gauchoride/assets/56096744/bf750ab9-b3a1-4a2f-9ef7-93c18a6aa8d5)

### Acceptance Criteria

- [x] The bad input and missing input error messages are added and improved
- [x] Example inputs on each form field

### Implementation Todos

- [x] Modify `DriverAvailabilityForm.js` to meet acceptance criterea.
