### ISSUE TITLE
Epic Part 3: Fix backend for DriverAvailabilities Create Page

### ISSUE THREAD

**Issue by diyaparm** [ucsb-cs156-s24/proj-gauchoride-s24-5pm-6#32]
_### As a...

driver

### I can...

Undestand what each of the form fields mean

### So that...

i can submit a correct availability without running into issues

### Discussion

The current create page for DriverAvailabilities has a number of aspects that should be improved. When create an availability we do not need to take the driver id as input, rather it should be automatically assigned to the creator.

### Implementation Todos

Issue 1 : Backend:
- [x] Modify `DriverAvailabilityController.java` `POST` so that when creating a new `DriverAvailability` we automatically use the creator's id and no longer take in id as an input.
- [x] Modify `DriverAvailabilityController.java` `PUT` so that when editing `DriverAvailability` we make sure that the `DriverAvailability` we intend to edit is really owned by the current user, and we no longer want to set the driver id to the incoming.
- [ ] Add the proper validations to `GET` single and `DELETE` so that a user can only delete or get their own availabilities and not anyone else
